fix

diff --git a/scripts/two-chainz b/scripts/two-chainz
--- a/scripts/two-chainz
+++ b/scripts/two-chainz
@@ -2,7 +2,7 @@
 # two-chainz creates two gaiad chains and configures the relayer to 
 
 SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-GAIA_DATA="$(pwd)/data"
+CHAIN_DATA="$(pwd)/data"
 RELAYER_DIR="$(dirname $SCRIPTDIR)"
 RELAYER_CONF="$HOME/.relayer"
 
@@ -12,9 +12,16 @@ if ! [ -x "$(which gaiad)" ]; then
   exit 1
 fi
 
+# Ensure iris is installed
+if ! [ -x "$(which iris)" ]; then
+  echo "Error: iris is not installed. " >&2
+  exit 1
+fi
+
 # Display software version for testers
-echo "GAIA VERSION INFO:"
-gaiad version --long
+echo "IRIS & GAIA VERSION INFO:"
+gaiad version
+iris version
 
 # Ensure jq is installed
 if [[ ! -x "$(which jq)" ]]; then
@@ -24,7 +31,7 @@ if [[ ! -x "$(which jq)" ]]; then
 fi
 
 # Ensure user understands what will be deleted
-if [[ -d $GAIA_DATA ]] && [[ ! "$1" == "skip" ]]; then
+if [[ -d $CHAIN_DATA ]] && [[ ! "$1" == "skip" ]]; then
   read -p "$(basename $0) will delete \$(pwd)/data and \$HOME/.relayer folders. Do you wish to continue? (y/n): " -n 1 -r
   echo
   if [[ ! $REPLY =~ ^[Yy]$ ]]; then
@@ -33,25 +40,25 @@ if [[ -d $GAIA_DATA ]] && [[ ! "$1" == "skip" ]]; then
 fi
 
 # Delete data from old runs
-rm -rf $GAIA_DATA &> /dev/null
+rm -rf $CHAIN_DATA &> /dev/null
 rm -rf $RELAYER_CONF &> /dev/null
 
-# Stop existing gaiad processes
+# Stop existing gaiad and iris processes
 killall gaiad &> /dev/null
-killall akash &> /dev/null
+killall iris &> /dev/null
 
 set -e
 
-chainid0=ibc-0
-chainid1=ibc-1
+chainid0=atom
+chainid1=iris
 
-echo "Generating gaia configurations..."
-mkdir -p $GAIA_DATA && cd $GAIA_DATA && cd ../
+echo "Generating gaia and iris configurations..."
+mkdir -p $CHAIN_DATA && cd $CHAIN_DATA && cd ../
 ./scripts/one-chain gaiad $chainid0 ./data 26657 26656 6060 9090
-./scripts/one-chain gaiad $chainid1 ./data 26557 26556 6061 9091
+./scripts/one-chain iris $chainid1 ./data 26557 26556 6061 9091
 
-[ -f $GAIA_DATA/$chainid0.log ] && echo "$chainid0 initialized. Watch file $GAIA_DATA/$chainid0.log to see its execution."
-[ -f $GAIA_DATA/$chainid1.log ] && echo "$chainid1 initialized. Watch file $GAIA_DATA/$chainid1.log to see its execution."
+[ -f $CHAIN_DATA/$chainid0.log ] && echo "$chainid0 initialized. Watch file $CHAIN_DATA/$chainid0.log to see its execution."
+[ -f $CHAIN_DATA/$chainid1.log ] && echo "$chainid1 initialized. Watch file $CHAIN_DATA/$chainid1.log to see its execution."
 
 cd $RELAYER_DIR
 
@@ -62,11 +69,11 @@ echo "Generating rly configurations..."
 rly config init
 rly config add-dir configs/demo/
 
-SEED0=$(jq -r '.mnemonic' $GAIA_DATA/ibc-0/key_seed.json)
-SEED1=$(jq -r '.mnemonic' $GAIA_DATA/ibc-1/key_seed.json)
-echo "Key $(rly keys restore ibc-0 testkey "$SEED0") imported from ibc-0 to relayer..."
-echo "Key $(rly keys restore ibc-1 testkey "$SEED1") imported from ibc-1 to relayer..."
+SEED0=$(jq -r '.mnemonic' $CHAIN_DATA/atom/key_seed.json)
+SEED1=$(jq -r '.mnemonic' $CHAIN_DATA/iris/key_seed.json)
+echo "Key $(rly keys restore atom testkey "$SEED0") imported from atom to relayer..."
+echo "Key $(rly keys restore iris testkey "$SEED1") imported from iris to relayer..."
 echo "Creating light clients..."
 sleep 3
-rly light init ibc-0 -f
-rly light init ibc-1 -f
+rly light init atom -f
+rly light init iris -f
